In [1]:
"""dython 설치를 0.5.1로 해야 함"""
%reload_ext autoreload
%autoreload 2 
from model.Tabular_GAN import Tabular_GAN
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import glob
import importlib

In [4]:
num_exp = 4

dataset = "shoppers"
real_path = f"CHECK_DATASETS/{dataset}/trn_{dataset}_final.csv"
fake_file_root = f"Fake_Datasets/{dataset}"
categorical_columns = ['SpecialDay', 'Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType', 'Weekend', 'Revenue']

In [5]:
"""종속변수는 categorical columns와 problem_type에만 넣어야 함"""
synthesizer =  Tabular_GAN(raw_csv_path = real_path, 
                     categorical_columns = categorical_columns,
                     epochs=200, 
                     batch_size=500, 
                     bins=5,
                     private_bool = False)

for i in range(num_exp):
    synthesizer.fit()
    syn = synthesizer.generate_samples()
    syn.to_csv(fake_file_root+"/"+"Shoppers_fake_{dataset}_{exp}.csv".format(dataset = dataset, exp=i+1), index= False)

Data Load
Data reorder
Fitting
### Transform begin
### Transform complete
# Condition output
(tensor([ 4,  9, 11, 17, 23, 26, 31, 39, 44], device='cuda:0'),)
(tensor([ 3,  7, 12, 18, 22, 27, 33, 38, 43], device='cuda:0'),)
tensor([0., 0., 0., 1., 1., 1., 1., 1., 1.], device='cuda:0')

# Condition output
(tensor([ 3,  7, 12, 17, 24, 29, 34, 37, 43], device='cuda:0'),)
(tensor([ 3,  7, 13, 18, 22, 28, 33, 37, 43], device='cuda:0'),)
tensor([0., 0., 0., 1., 1., 1., 1., 1., 1.], device='cuda:0')

Epoch 1, Loss G:  3.5217, Loss D: -0.0219
#### cross_entropy : tensor(1.8547)
## continuous_entropy : tensor(1.6492)
## continuous_forecasting_entropy : tensor(0.0102)
## loss_info   : tensor(1.4370)

# Condition output
(tensor([ 4,  9, 11, 16, 20, 25, 30, 39, 43], device='cuda:0'),)
(tensor([ 4,  7, 12, 17, 22, 27, 32, 37, 43], device='cuda:0'),)
tensor([0., 0., 0., 1., 1., 1., 1., 1., 1.], device='cuda:0')

# Condition output
(tensor([ 4,  8, 12, 17, 20, 25, 30, 39, 44], device='cuda:0'),)
(tens